# 配置网关
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**  # 访问user路径转发用户服务
          filters:
            - StripPrefix=1 # 转发之前去掉1层路径
#logging:
#  level:
#    root: debug
#    sun.rmi.: ERROR
#    com.alibaba.nacos.client.naming: error
#    sun.net.www.protocol.http.HttpURLConnection: error
#        - id: data-service
#          uri: lb://data-service
#          predicates:
#            - Path=/data/**
#          filters:
#            - StripPrefix=1
#        - id: search-service
#          uri: lb://search-service
#          predicates:
#            - Path=/search/**
#          filters:
#            - StripPrefix=1


